name: secrets-revert
on:
  workflow_dispatch:
    inputs:
      REVERT_COMMIT:
        type: string
        description: 'REVERT_COMMIT: long commit to revert'
        required: true

permissions:
  contents: write

concurrency:
  group: secrets
  cancel-in-progress: true

jobs:
  secrets-revert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: "main"
        submodules: "true"
        token: "${{ vars.BOT_GITHUB_TOKEN }}"
    - uses: ./.github/actions/setup
    - uses: ./.github/actions/run-playbook
      with:
        playbook_tag: "secrets-git-revert"
        playbook_extravar_secrets_revert_commit: "${{ github.event.inputs.REVERT_COMMIT }}"
        gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
