name: secrets-git
on:
  workflow_dispatch:
    inputs:
      GIT_CMDARGS:
        type: string
        description: 'GIT_CMDARGS: git command arguments'
        required: true
      GIT_COMMITMSG:
        type: string
        description: 'GIT_COMMITMSG: commit message for your changes. Set GIT_PUSH to true if you want to push your commit'
        required: false
        default: ''
      GIT_PUSH:
        type: boolean
        description: 'GIT_PUSH: do we push the changes after running the `git` command ?'
        required: false
        default: false

permissions:
  contents: write

concurrency:
  group: secrets
  cancel-in-progress: true

jobs:
  secrets-git:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: "main"
        submodules: "true"
        token: "${{ vars.BOT_GITHUB_TOKEN }}"
    - uses: ./.github/actions/setup
    - uses: ./.github/actions/run-playbook
      with:
        playbook_tag: "secrets-git"
        playbook_extravar_secrets_git_cmdargs: "${{ github.event.inputs.GIT_CMDARGS }}"
        playbook_extravar_secrets_git_commitmsg: "${{ github.event.inputs.GIT_COMMITMSG }}"
        playbook_extravar_secrets_git_push: "${{ github.event.inputs.GIT_PUSH }}"
        gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
