name: secrets-delete
on:
  workflow_dispatch:
    inputs:
      DELETE_PATH:
        type: string
        description: 'DELETE_PATH: path to the password to remove'
        required: true

permissions:
  contents: write

concurrency:
  group: secrets
  cancel-in-progress: true

jobs:
  secrets-delete:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: "main"
        submodules: "true"
        token: "${{ vars.BOT_GITHUB_TOKEN }}"
    - uses: ./.github/actions/setup
    - uses: ./.github/actions/run-playbook
      with:
        playbook_tag: "secrets-delete"
        playbook_extravar_secrets_delete_path: "${{ github.event.inputs.DELETE_PATH }}"
        gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
