name: secrets-generate
on:
  workflow_dispatch:
    inputs:
      GENERATE_PATH:
        type: string
        description: 'GENERATE_PATH: path to the password to generate'
        required: true
      GENERATE_LEN:
        type: number
        description: 'GENERATE_LEN: length of the password to generate'
        default: 24
        required: false

permissions:
  contents: write

concurrency:
  group: secrets
  cancel-in-progress: true

jobs:
  secrets-generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: "main"
        submodules: "true"
        token: "${{ vars.BOT_GITHUB_TOKEN }}"
    - uses: ./.github/actions/setup
    - uses: ./.github/actions/run-playbook
      with:
        playbook_tag: "secrets-generate"
        playbook_extravar_secrets_generate_path: "${{ github.event.inputs.GENERATE_PATH }}"
        playbook_extravar_secrets_generate_len: "${{ github.event.inputs.GENERATE_LEN }}"
        gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
