name: secrets-move
on:
  workflow_dispatch:
    inputs:
      MOVE_OLDPATH:
        type: string
        description: 'MOVE_OLDPATH: password or directory to move'
      MOVE_NEWPATH:
        type: string
        description: 'MOVE_NEWPATH: password or directory destination'

permissions:
  contents: write

concurrency:
  group: secrets
  cancel-in-progress: true

jobs:
  secrets-move:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: "main"
        submodules: "true"
        token: "${{ vars.BOT_GITHUB_TOKEN }}"
    - uses: ./.github/actions/setup
    - uses: ./.github/actions/run-playbook
      with:
        playbook_tag: "secrets-move"
        playbook_extravar_secrets_move_oldpath: "${{ github.event.inputs.MOVE_OLDPATH }}"
        playbook_extravar_secrets_move_newpath: "${{ github.event.inputs.MOVE_NEWPATH }}"
        gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
