name: secrets-add
on:
  workflow_dispatch:
    inputs:
      ADD_PATH:
        type: string
        description: 'ADD_PATH: path to the new password'
        required: true
      ADD_PASSWORD:
        type: string
        description: 'ADD_PASSWORD: password to insert'
        required: true

permissions:
  contents: write

concurrency:
  group: secrets
  cancel-in-progress: true

jobs:
  secrets-add:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: "main"
        submodules: "true"
        token: "${{ vars.BOT_GITHUB_TOKEN }}"
    - uses: ./.github/actions/setup
    - uses: ./.github/actions/run-playbook
      with:
        playbook_tag: "secrets-add"
        playbook_extravar_secrets_add_path: "${{ github.event.inputs.ADD_PATH }}"
        playbook_extravar_secrets_add_password: "${{ github.event.inputs.ADD_PASSWORD }}"
        gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
